### ISSUE TITLE
Urgent Concern (see the attached image)

### ISSUE THREAD

**Issue by CozzyBro2** [NotSoClassy/lau#1]
Delete this respository 
![ponder](https://user-images.githubusercontent.com/76234965/110859234-26eb0900-8289-11eb-9e81-e637aa3c156e.png)

**Comment by NotSoClassy** [comment]
They deprecated deleting repos :pensive:

**Comment by CozzyBro2** [comment]
u cock!!! 😡😡😡

![image](https://user-images.githubusercontent.com/76234965/110859791-f9528f80-8289-11eb-902a-66f204254213.png)

u kan just delet it!!!!! 😡😡😡👊👊

**Comment by NotSoClassy** [comment]
they only deprecated it for good repos

**Comment by CozzyBro2** [comment]
![trollKkkat](https://user-images.githubusercontent.com/76234965/110885562-15b7f180-82b5-11eb-8a25-4aa6a9520800.png)
![trollcatHot](https://user-images.githubusercontent.com/76234965/110885563-15b7f180-82b5-11eb-89c5-73966b2fe4c5.png)
![camadaMad](https://user-images.githubusercontent.com/76234965/110885564-16508800-82b5-11eb-8835-84d18527eacc.png)
![ponder](https://user-images.githubusercontent.com/76234965/110885565-16508800-82b5-11eb-9771-7ddb0abdad37.png)
![Uploading pepeHappy2.png…]()
